### ISSUE TITLE
[meta] other crowd cookbook

### ISSUE THREAD

**Issue by patcon** [afklm/chef_crowd#2]
What's this cookbook's relation to https://github.com/QVCItalia/chef-crowd?

I'm evaluating options. Thanks :)

**Comment by mvdkleijn** [comment]
No real relationship. The cookbooks were developed independently from each other. When we were looking for a crowd cookbook we did not come across the QVCItalia one so we developed our own. Our cookbook is used in production, is actively maintained and listed on the Chef supermarket.

**Comment by patcon** [comment]
:+1: thanks

**Comment by mrjcleaver** [comment]
Do you consider it still to be in production and actively maintained?

I ask as we have several open pull requests.

Thanks,
   Martin.

**Comment by mvdkleijn** [comment]
@mrjcleaver apologies, you're correct to point rhis out. We have a small team here and have spent too little time on this. I will endeavour to correct this situation.
